//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Translation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        internal static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achetez Déjà.
        /// </summary>
        internal static string AchetezMaintenant {
            get {
                return ResourceManager.GetString("AchetezMaintenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide-moi.
        /// </summary>
        internal static string Aide {
            get {
                return ResourceManager.GetString("Aide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        internal static string AjouterChariot {
            get {
                return ResourceManager.GetString("AjouterChariot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer Coupon.
        /// </summary>
        internal static string AppliquerCoupon {
            get {
                return ResourceManager.GetString("AppliquerCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        internal static string Apropos {
            get {
                return ResourceManager.GetString("Apropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutique.
        /// </summary>
        internal static string Boutique {
            get {
                return ResourceManager.GetString("Boutique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulletin.
        /// </summary>
        internal static string Bulletin {
            get {
                return ResourceManager.GetString("Bulletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chariot.
        /// </summary>
        internal static string Chariot {
            get {
                return ResourceManager.GetString("Chariot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Promo.
        /// </summary>
        internal static string CouponCode {
            get {
                return ResourceManager.GetString("CouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de bas en haut.
        /// </summary>
        internal static string DeBasEnHaut {
            get {
                return ResourceManager.GetString("DeBasEnHaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre.
        /// </summary>
        internal static string Filtre {
            get {
                return ResourceManager.GetString("Filtre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtres.
        /// </summary>
        internal static string Filtres {
            get {
                return ResourceManager.GetString("Filtres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haut en bas.
        /// </summary>
        internal static string HautEnBas {
            get {
                return ResourceManager.GetString("HautEnBas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatique.
        /// </summary>
        internal static string Informatique {
            get {
                return ResourceManager.GetString("Informatique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalle.
        /// </summary>
        internal static string Intervalle {
            get {
                return ResourceManager.GetString("Intervalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liens.
        /// </summary>
        internal static string Liens {
            get {
                return ResourceManager.GetString("Liens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison gratuit partout au Québec.
        /// </summary>
        internal static string LivraisonMessage {
            get {
                return ResourceManager.GetString("LivraisonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meuble.
        /// </summary>
        internal static string Meuble {
            get {
                return ResourceManager.GetString("Meuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour panier.
        /// </summary>
        internal static string MiseJourPanier {
            get {
                return ResourceManager.GetString("MiseJourPanier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string msgAlerte {
            get {
                return ResourceManager.GetString("msgAlerte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string msgErreur {
            get {
                return ResourceManager.GetString("msgErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string msgInformation {
            get {
                return ResourceManager.GetString("msgInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        internal static string Nouveau {
            get {
                return ResourceManager.GetString("Nouveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveaux produits.
        /// </summary>
        internal static string NouveauxProduits {
            get {
                return ResourceManager.GetString("NouveauxProduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularité.
        /// </summary>
        internal static string Popularite {
            get {
                return ResourceManager.GetString("Popularite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        internal static string Prix {
            get {
                return ResourceManager.GetString("Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        internal static string Produit {
            get {
                return ResourceManager.GetString("Produit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allez-y et ajoutez quelque chose !!!.
        /// </summary>
        internal static string ProfitezVous {
            get {
                return ResourceManager.GetString("ProfitezVous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantite.
        /// </summary>
        internal static string Quantite {
            get {
                return ResourceManager.GetString("Quantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche de produits....
        /// </summary>
        internal static string RechercheProduits {
            get {
                return ResourceManager.GetString("RechercheProduits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        internal static string Tous {
            get {
                return ResourceManager.GetString("Tous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tri par défaut.
        /// </summary>
        internal static string TriParDefaut {
            get {
                return ResourceManager.GetString("TriParDefaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vêtement.
        /// </summary>
        internal static string Vetement {
            get {
                return ResourceManager.GetString("Vetement", resourceCulture);
            }
        }
    }
}
